# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Answer_text',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
